Cargo.lock
runtime_v9/Cargo.toml
runtime_v9/src/runtime/policy.rs

Using a BigInt serializer from the `num` feature does work; however, it's not very pretty for huge numbers. E.g., `32 << 30` shows in TOML as `minimum_consensus_power = [1, [0, 2560]]`. On the other side it's alright for most cases like `1 << 20` `minimum_verified_allocation_size = [1, [1048576]]`.
Given that we seldom change those parameters, I propose we use a no-code solution.
Closes https://github.com/ChainSafe/fil-actor-states/issues/2

fix serde for Policy BigInt

---

.github/workflows/tests.yml
Makefile

- clippy was running twice for no reason
- `clean-all` was doing the same stuff as `clean`
- missing phony targets
Closes 

improve lint checks

---

.github/dependabot.yml
.github/workflows/cancel-stale.yml
.github/workflows/tests.yml

- Add `dependabot.yml`
- Add `cancel-stale.yml`
- Fix [CI workflow error](https://github.com/ChainSafe/fil-actor-states/actions/runs/4439393585/jobs/7791799816#step:12:1)
- Speed up `build-test` job by adding sccache action
- Replace `--all` with `--workspace` (--all          Alias for --workspace (deprecated))
- Run CI on push to main branch, otherwise sccache action could not fetch build cache for a new PR
```console
Error: .github/workflows/tests.yml (Line: 46, Col: [2](https://github.com/ChainSafe/fil-actor-states/actions/runs/4439393585/jobs/7791799816#step:12:2)6):
Error: .github/workflows/tests.yml (Line: 46, Col: 26): Unexpected value ''
Error: An error occurred when attempting to determine the step timeout.
Error: …
```

fix(ci): fix ci manifest errors

---

Cargo.lock
Cargo.toml

- So that we could upgrade `fvm` from `"~2.2"` to `"~2.3"` in `forest`
Closes 

fix: relax fvm2 version constraints

---

.github/workflows/tests.yml
Cargo.lock
Cargo.toml
Makefile
fil_actor_interface/tests/dummy.rs

- Remove `opencl` dependency
- Cleanup CI `opencl` installation steps
- Regression tests
With this being merged, I think it's possible to remove `opencl` dependency from `forest` as well
Closes 

feat: remove opencl dependency

---

Cargo.lock
Cargo.toml
fil_actor_interface/Cargo.toml
fil_actor_interface/src/builtin/miner/mod.rs

- Removed use of  `libp2p_identity::PeerId`
Closes #24 

Refactor the interface to avoid depending on libp2p

---

Cargo.lock
Cargo.toml

- fvm_shared 3.2 has been released and is not strictly backwards compatible.
Closes 

fix: pin fvm_shared to 3.1

---

.gitmodules
Cargo.lock
Cargo.toml
power_v10/src/state.rs

- bump dependency from 3.1 to 3.2
- forest has to be updated as well so I've temporarily pointed the submodule to an updated branch
Closes 

chore: bump fvm_shared3 dependency

---

Cargo.toml

- Pin `fvm_shared` to v2.3 as v2.4 does not have backward compatibility
Closes 

Pin fvm-shared to v2.3

---

Cargo.lock
Cargo.toml

- remove fvm, it wasn't used in these crates at all. Surprised we don't check for unused deps with e.g `cargo-udeps`, which would have stopped this situation.
- bump fvm_shared
Closes 

fixup deps for forest/stable-rust-toolchain

---

Cargo.lock
actors/init/Cargo.toml
actors/init/src/v0/mod.rs
actors/init/src/v0/state.rs
actors/init/src/v0/types.rs
fil_actor_interface/Cargo.toml
fil_actor_interface/src/builtin/known_cids.rs

- Use fvm crates instead of forest crates in init v0 actor
Closes #129 

Remove forest specific dependencies from init v0 actor

---

scripts/publish.sh

When running `publish.sh` on `ubuntu-latest` we end up using all disk space currently on that machine.
- Added a `cargo clean` after every crate is published
Closes 

Fix no space left issue on publishing crates

---

.gitmodules

- use `main` in the forest submodule.
Closes 

chore: revert submodule to `main` branch

---

.github/CODEOWNERS

We've got a new review assignment system - two per PR, which is out-of-repo.

fix: do not assign everyone to review every pr

---

.github/workflows/tests.yml
Cargo.lock
Cargo.toml
Makefile
fil_actors_shared/Cargo.toml
fil_actors_shared/src/lib.rs
fil_actors_shared/src/v10/mod.rs
fil_actors_shared/src/v11/mod.rs
fil_actors_shared/src/v8/mod.rs
fil_actors_shared/src/v9/mod.rs
rust-toolchain.toml

Part of https://github.com/ChainSafe/forest/issues/3478 and https://github.com/ChainSafe/forest/issues/3422
- Upgrade non-fvm crates
- Upgrade `fvm_ipld_bitfield`
- Update `fvm` and `fvm_shared` (with partial nv21 support before fvm4 is landed)
- Re-export `fvm*` crates
- Update CI to work with the latest `forest` code
Closes 
Upgrade on `forest` side: https://github.com/ChainSafe/forest/pull/3481

chore(deps): upgrade dependencies

---

.github/workflows/tests.yml

- we're missing `merge_group` in workflows. Without it, the jobs in the merge queue are not being run.
Closes 

add merge group to workflows

---

.github/workflows/tests.yml

- use `fuzzy` instead of `buildjet`. It shouldn't require much of its resources and frees us completely from `buildjet` bills.
Closes 

use fuzzy instead of buildjet

---

.github/workflows/tests.yml

This reverts commit 35350701d65e1d6e8c2fde3001b5b443032d6720.
- there seems to be a wild race on the Cargo file with the `fuzzy` as worker. The file is mixed with Forest Cargo file. [Cargo.toml](https://github.com/ChainSafe/fil-actor-states/files/12892836/Cargo.toml.txt). Full error: https://github.com/ChainSafe/fil-actor-states/actions/runs/6506927548/job/17674105715?pr=183
Closes 

Revert "use fuzzy instead of buildjet (#176)"

---

actors/power/src/v8/state.rs
actors/verifreg/src/v9/state.rs
fil_actor_interface/src/builtin/miner/mod.rs
fil_actor_interface/src/builtin/power/mod.rs

- Added missing traits `Eq, PartialEq, PartialOrd, Ord, Hash` for  `Claim` and `MinerPower`
Closes #189 

Add missing traits for Claim and MinerPower

---

Cargo.lock
Cargo.toml

- bump versions of `fvm_shared@4` and others
- update `forest` submodule to use the latest commit on main (to better test the version bump change)
Closes 

chore(deps): bump versions of `fvm_shared@4` and others

---

fil_actor_interface/src/builtin/miner/mod.rs

- Expose 4 new fields in `SectorOnChainInfo`.
Note, these fields are the union of fields available through version v9 to v12. The newest actors do not have all of these fields, but we still need to report them.
Closes 

feat: expose superset of SectorOnChainInfo fields

---

Cargo.lock
actors/account/Cargo.toml
actors/cron/Cargo.toml
actors/datacap/Cargo.toml
actors/eam/Cargo.toml
actors/ethaccount/Cargo.toml
actors/evm/Cargo.toml
actors/init/Cargo.toml
actors/market/Cargo.toml
actors/miner/Cargo.toml
actors/multisig/Cargo.toml
actors/paych/Cargo.toml
actors/power/Cargo.toml
actors/reward/Cargo.toml
actors/system/Cargo.toml
actors/verifreg/Cargo.toml
fil_actor_interface/Cargo.toml
fil_actor_interface/builtin_actors_gen.go
fil_actors_shared/Cargo.toml

Prepare v7.0.0 release

---

fil_actor_interface/src/builtin/miner/mod.rs

- Added 2 new methods `partitions_posted` and `disputable_proof_count` required for `Filecoin.StateMinerDeadlines`
Part of https://github.com/ChainSafe/forest/pull/3761

New methods for Miner Deadline

---

actors/miner/src/v10/deadline_info.rs
actors/miner/src/v11/deadline_info.rs
actors/miner/src/v12/deadline_info.rs
actors/miner/src/v8/deadline_info.rs
actors/miner/src/v9/deadline_info.rs
fil_actor_interface/src/builtin/miner/mod.rs

- Expose a standardized interface to `DeadlineInfo` from the miner actor.
Closes 

feat: make `DeadlineInfo` available in the miner interface

---

fil_actor_interface/src/builtin/miner/mod.rs

- Add a `Partition::recovering_sectors` method
Needed for https://github.com/ChainSafe/forest/pull/3779
Closes 

Add a `Partition::recovering_sectors` method

---

fil_actor_interface/src/builtin/known_cids.rs
rust-toolchain.toml

upgrade rust toolchain to 1.75.0 to align with forest repository
- Fix all clippy warnings
Closes 
https://releases.rs/docs/1.75.0/

chore: upgrade rust toolchain to 1.75.0

---

Cargo.lock
actors/multisig/src/v12/state.rs
actors/multisig/src/v12/types.rs
fil_actor_interface/Cargo.toml
fil_actor_interface/src/builtin/multisig/mod.rs
fil_actor_interface/src/lib.rs
fil_actor_interface/src/macros.rs

- Added `get_pending_txn` method required for `MsigGetPending` [rpc](https://github.com/ChainSafe/forest/pull/3838)
- Use `fvm_shared4` instead of `fvm_shared` for multisig v12 
Closes 

Add get pending transaction method for multisig

---

Cargo.lock
fil_actor_interface/src/builtin/market/mod.rs
fil_actor_interface/src/convert.rs

- Implement `State::states`, `State::proposals`, `DealProposals::for_each`, `DealStates::get`, ... methods to properly implement Forest `StateMarketStorageDeal` RPC method ([related PR](https://github.com/ChainSafe/forest/pull/3815)).
- Update `derive` macros for `DealProposal` and `DealState`.
N/A

Changes to market state for Forest `StateMarketStorageDeal` RPC method

---

.github/workflows/publish.yml

- Releases are now made via UI, so this step is not required in publish workflow
https://github.com/ChainSafe/fil-actor-states/pull/249
Closes 

Remove pre release creation from publish workflow

---

fil_actor_interface/src/builtin/market/mod.rs

This PR contains necessary fixes to unblock https://github.com/ChainSafe/forest/pull/4079
- implement `fn DealProposals::get`
- implement `const fn DealState::empty`
- fix `fn market::State::proposals`
Closes 

feat: add missing methods for implementing Filecoin.StateMarketStorageDeal

---

Cargo.lock
Cargo.toml
actors/datacap/Cargo.toml
actors/evm/Cargo.toml
actors/init/Cargo.toml
actors/market/Cargo.toml
actors/miner/Cargo.toml
actors/multisig/Cargo.toml
actors/paych/Cargo.toml
actors/power/Cargo.toml
actors/system/Cargo.toml
actors/verifreg/Cargo.toml
fil_actor_interface/Cargo.toml

- Include https://github.com/ChainSafe/fil-actor-states/pull/267 to unblock https://github.com/ChainSafe/forest/pull/4079
- bump `base64` and `itertools` to match their versions in `forest`
Closes 

chore: prepare release v10.0.0-dev.5

---

fil_actors_shared/src/v12/util/map.rs
fil_actors_shared/src/v13/util/map.rs
rust-toolchain.toml

- bump rust-toolchain to `1.76.0` to match forest
Closes 

chore: bump rust-toolchain to match forest

---

.github/workflows/publish.yml

The `publish crates` job should not take ~15mins (https://github.com/ChainSafe/fil-actor-states/actions/workflows/publish.yml)
- `sccache` was not working without `RUSTC_WRAPPER=sccache` 
Closes 
https://github.com/Mozilla-Actions/sccache-action?tab=readme-ov-file#rust-code

fix(ci): setup sccache env var properly in publish.yml

---

.taplo.toml
rust-toolchain.toml

- bump rust toolchain to 1.77.0
- update forest submodule
- update taplo config to ignore forest submodule
Closes 

chore(toolchain): bump rust toolchain to 1.77.0

---

Cargo.lock
Cargo.toml
actors/datacap/Cargo.toml
actors/evm/Cargo.toml
actors/init/Cargo.toml
actors/market/Cargo.toml
actors/miner/Cargo.toml
actors/multisig/Cargo.toml
actors/paych/Cargo.toml
actors/power/Cargo.toml
actors/system/Cargo.toml
actors/verifreg/Cargo.toml
fil_actor_interface/Cargo.toml
fil_actor_interface/builtin_actors_gen.go
fil_actor_interface/src/builtin/miner/mod.rs
fil_actor_interface/src/builtin/verifreg/mod.rs

- prepare release v10.1.0 for the calibration network patch
- added new cids for v13.0.0,
- added old verifreg as exception (same as we did with miner back with watermelon fixes)
Closes 

Prepare release 10.1.0

---

fil_actor_interface/src/builtin/reward/mod.rs

- Return a pointer to `this_epoch_baseline_power` to make the api more efficient.
Closes 
```rust
let (min, max) = reward_state.deal_provider_collateral_bounds(
policy,
size,
power_claim.raw_byte_power,
reward_state. this_epoch_baseline_power(), // <--- This needs to be non-consuming. 
supply.into(),
);
```

[Fix] Don't consume on reward state on this_epoch_baseline_power.

---

fil_actor_interface/src/builtin/verifreg/mod.rs

- Added `verifier_data_cap` verifreg actor method required for `Filecoin.StateVerifierStatus` rpc
part of [#4319](https://github.com/ChainSafe/forest/pull/4319)

Add verifier_data_cap method for verifreg actor

---

fil_actor_interface/src/builtin/miner/mod.rs
fil_actor_interface/src/builtin/power/mod.rs
fil_actor_interface/src/builtin/reward/mod.rs
fil_actor_interface/src/convert.rs
fil_actor_interface/src/lib.rs
fil_actors_shared/src/v10/runtime/policy.rs
fil_actors_shared/src/v11/runtime/policy.rs
fil_actors_shared/src/v12/runtime/policy.rs
fil_actors_shared/src/v13/runtime/policy.rs
fil_actors_shared/src/v9/runtime/policy.rs

- :warning: this is a breaking change, a major version bump will be required,
- remove network definitions from the policies - they were incorrect, introduced unnecessary coupling, strived away from the original implementation and were by large re-defined in Forest itself.
- make `v13` policy the default, exported one.
Close
Corresponding Forest PR https://github.com/ChainSafe/forest/pull/4325

chore: no network in policies + use v13 as export

---

fil_actor_interface/src/builtin/verifreg/mod.rs

- Introduces `get_claim` method for `verifreg` actor.
work on https://github.com/ChainSafe/forest/issues/4336

[Feature] Verifreg get_claim.

---

Cargo.toml
actors/datacap/Cargo.toml
actors/evm/Cargo.toml
actors/init/Cargo.toml
actors/market/Cargo.toml
actors/miner/Cargo.toml
actors/multisig/Cargo.toml
actors/paych/Cargo.toml
actors/power/Cargo.toml
actors/reward/Cargo.toml
actors/system/Cargo.toml
actors/verifreg/Cargo.toml
fil_actor_interface/Cargo.toml
fil_actor_interface/src/builtin/miner/mod.rs
fil_actor_interface/src/lib.rs

-  add `fn miner::State::get_sector` to unblock https://github.com/ChainSafe/forest/pull/4381
- bump crate minor versions
- refactor `Cargo.toml`s to not require updating >1 `Cargo.toml` files for future version bumps
- bump forest submodule
Closes 

feat: add `fn miner::State::get_sector`

---

Cargo.toml
fil_actor_interface/src/builtin/verifreg/mod.rs

Bug fix to unblock https://github.com/ChainSafe/forest/pull/4401
- Fix a bug that `provider` and `client` fields are not properly assigned
- Bump patch versions
- Bump forest submodule
Closes 

fix: bug in verifreg::Claim conversion logic

---

actors/paych/src/v10/types.rs
actors/paych/src/v11/types.rs
actors/paych/src/v12/types.rs
actors/paych/src/v13/types.rs
actors/paych/src/v8/types.rs
actors/paych/src/v9/types.rs
rust-toolchain.toml

- bump rust toolchain to 1.79.0
- fix clippy warnings
- update forest submodule
Closes 

chore: bump rust toolchain

---

Cargo.toml
fil_actors_shared/Cargo.toml
fil_actors_shared/src/lib.rs
scripts/publish.sh

- bump `fvm_shared@4` version to `4.3`
- bump `fvm_shared@3` version to `3.10`
- bump `fvm_shared@2` version to `2.7`
- bump `frc46_token`, `frc42_macros` and `filecoin-proofs-api` versions
- re-export `fvm_shared4`, `frc46_token` and `filecoin_proofs_api`
- bump crate versions to `14.0.0`
`forest` integration tests are green in https://github.com/ChainSafe/forest/pull/4416
Closes 

chore(deps): bump fvm_shared@4

---

.github/workflows/publish.yml
.github/workflows/tests.yml
scripts/publish.sh

To resume publishing `v14.0.0` and unblock https://github.com/ChainSafe/forest/pull/4416
The publish failed for the non-existing `fil_actor_evm_shared_state` : https://github.com/ChainSafe/fil-actor-states/actions/runs/9583961899/job/26426418571#step:4:1196
-  ~add `cargo-publish-dry-run` job~ This won't work when a PR contains version bump
- fix `publish.sh` by removing the non-existing `fil_actor_evm_shared_state`
- simplify `publish.sh` by removing the `cargo metadata` steps
- bump `mozilla-actions/sccache-action`
- disable sccache GHA backend for better publishing performance
- remove cargo clean step for better publishing performance
Closes 

fix: publish script

---

fil_actors_shared/src/v10/util/mapmap.rs
fil_actors_shared/src/v11/util/mapmap.rs
fil_actors_shared/src/v9/util/mapmap.rs

- Introduces the ability to iterate outer keys of the double map.

[Feature] Backport outer map iteration for MapMap.

---

Cargo.toml

- prepare release `16.0.0` because of the breaking change of https://github.com/ChainSafe/fil-actor-states/pull/319. Relevant Forest PR to address these changes is in https://github.com/ChainSafe/forest/pull/4564
Closes 

release: prepare 16.0.0

---

fil_actors_shared/src/v13/vm_api/mod.rs
fil_actors_shared/src/v14/runtime/mod.rs
fil_actors_shared/src/v14/vm_api/mod.rs
rust-toolchain.toml

- upgrade rust toolchain to 1.80.0
- upgrade forest submodule
- fix clippy warnings
Closes 

chore: upgrade rust toolchain to 1.80.0

---

Cargo.toml
fil_actor_interface/Cargo.toml
fil_actors_shared/Cargo.toml

Some dependencies are no longer needed but weren't cleaned in the past. Sadly, the tooling I used to assert this is lacking;
- `cargo udeps` had lots of false negatives
- our ruby script had lots of false positives
With some back and forth with the compiler, I managed to prune the dependencies a bit. It compiles fine on Forest `shashank/v15-builtin-actors`.
Closes 

chore: prune deps

---

Cargo.toml

- the current requirement is a bit strict for a library. If I want to update the FVM to, e.g., `4.3.3` in Forest, I'd need to do it also here, go through release process etc. This PR relaxes the requirement so that the binary _chooses_ the right minor version.
Part of https://github.com/ChainSafe/forest/issues/4806

chore: relax FVM version requirement

---

rust-toolchain.toml

- upgrade rust toolchain to 1.82.0
- point Forest submodule to the latest main
Closes 

chore: upgrade rust toolchain to 1.82.0

---

actors/market/src/v10/state.rs
actors/market/src/v11/state.rs
actors/market/src/v12/state.rs
actors/market/src/v13/state.rs
actors/market/src/v14/state.rs
actors/market/src/v15/state.rs
actors/market/src/v16/state.rs
actors/market/src/v8/state.rs
actors/market/src/v9/state.rs
actors/reward/Cargo.toml
actors/reward/src/v11/state.rs
actors/reward/src/v12/state.rs
actors/reward/src/v13/state.rs
actors/reward/src/v14/state.rs
actors/reward/src/v15/state.rs
actors/reward/src/v16/state.rs

- Remove methods which are moved to forest shim
Closes #338 

Remove methods moved to forest shim

---

.gitmodules

- Now we have [v21 actors](https://github.com/ChainSafe/forest/pull/5423) merged in forest main we can revert to `main` branch
Part of https://github.com/ChainSafe/forest/issues/5136 

Revert to forest main branch

---

Cargo.toml
actors/cron/src/v10/mod.rs
actors/cron/src/v8/mod.rs
actors/cron/src/v9/mod.rs

- Add previously skipped `ConstructorParams ` for v8, v9 and v10 cron actor. 
- Needed for https://github.com/ChainSafe/forest/issues/5725
Closes 

Add previously skipped cron type

---

actors/init/Cargo.toml
actors/init/src/v10/mod.rs

- Replace the `ExecExported` with the `Exec4` for the `init` actor in compliance with the builtin-actor [v10](https://github.com/filecoin-project/builtin-actors/blob/f78bf08a1f444544c22a5dea4d329b88705b0c04/actors/init/src/lib.rs#L33) and go-state-type [v10](https://github.com/filecoin-project/go-state-types/blob/f0f90965d298d86739473f13196d6ff5bcdc2d47/builtin/v10/init/methods.go#L12)

Replace init actor v10 `ExecExported` method with Exec4

---

actors/miner/src/v14/types.rs

- Adds the `InternalSectorSetupForPresealParams` in miner v14 `types.rs`

Add missing `InternalSectorSetupForPresealParams` type in miner actor v14
