ChainSafe/fil-actor-states

- Cargo.lock
- Cargo.toml
- system_v10/Cargo.toml
- system_v10/src/lib.rs
- verifreg_v10/Cargo.toml
> System v10

- Cargo.lock
- Cargo.toml
- multisig_v10/Cargo.toml
- multisig_v10/src/lib.rs
- multisig_v10/src/state.rs
- multisig_v10/src/testing.rs
- multisig_v10/src/types.rs
> Multisig v10

- Cargo.lock
- Cargo.toml
- account_v10/Cargo.toml
- account_v10/src/lib.rs
- account_v10/src/state.rs
- account_v10/src/testing.rs
- account_v10/src/types.rs
> Account v10

- runtime_v10/src/runtime/policy.rs
> Fix Policy serialisation

- fil_actor_interface/src/builtin/ethaccount/mod.rs
- fil_actor_interface/src/builtin/mod.rs
- fil_actor_interface/src/builtin/placeholder/mod.rs
- Add ethaccount and placeholder
Contributes to #2628
> Add ethaccount and placeholder

- cron_v8/src/state.rs
- fil_actor_interface/src/builtin/account/mod.rs
- fil_actor_interface/src/builtin/cron/mod.rs
- fil_actor_interface/src/builtin/init/mod.rs
- fil_actor_interface/src/builtin/market/mod.rs
- fil_actor_interface/src/builtin/miner/mod.rs
- fil_actor_interface/src/builtin/multisig/mod.rs
- fil_actor_interface/src/builtin/power/mod.rs
- fil_actor_interface/src/builtin/reward/mod.rs
- fil_actor_interface/src/builtin/system/mod.rs
- init_v8/src/state.rs
- market_v8/src/state.rs
- miner_v8/src/state.rs
- multisig_v8/src/state.rs
- power_v8/src/state.rs
- reward_v8/src/state.rs
- system_v8/src/lib.rs
- Derive Debug trait for actor's
Contributes to https://github.com/ChainSafe/forest/issues/2639 
> Derive Debug for State type

- fil_actor_interface/src/builtin/account/mod.rs
- fil_actor_interface/src/builtin/init/mod.rs
- fil_actor_interface/src/builtin/market/mod.rs
- fil_actor_interface/src/builtin/miner/mod.rs
- fil_actor_interface/src/builtin/power/mod.rs
- fil_actor_interface/src/builtin/reward/mod.rs
- Updated v10 `mainnet` CID's
Closes #25 
> Updated v10 mainnet cid's

- Cargo.lock
- datacap_v10/src/state.rs
- fil_actor_interface/Cargo.toml
- fil_actor_interface/src/builtin/datacap/mod.rs
- fil_actor_interface/src/builtin/evm/mod.rs
- fil_actor_interface/src/builtin/mod.rs
- Added `datacap` and `evm` to `fil_actor_interface`
Contributes to https://github.com/ChainSafe/forest/issues/2634
> Add new v10 actors to fil actor interface

- fil_actor_interface/src/builtin/account/mod.rs
- fil_actor_interface/src/builtin/cron/mod.rs
- fil_actor_interface/src/builtin/init/mod.rs
- fil_actor_interface/src/builtin/market/mod.rs
- fil_actor_interface/src/builtin/miner/mod.rs
- fil_actor_interface/src/builtin/multisig/mod.rs
- fil_actor_interface/src/builtin/power/mod.rs
- fil_actor_interface/src/builtin/reward/mod.rs
- fil_actor_interface/src/builtin/system/mod.rs
- Removed `devnet` cid's as these are unused (Discussion thread: https://github.com/ChainSafe/fil-actor-states/pull/34)
> Remove devnet cids

- fil_actor_interface/src/builtin/evm/mod.rs
> Use correct evm calibnet cid

- fil_actor_interface/src/builtin/evm/mod.rs
- rust-toolchain.toml
- verifreg_v10/src/state.rs
- verifreg_v9/src/state.rs
- All code changes come from `cargo clippy --fix`
Closes 
> upgrade rust to 1.70-nightly

- runtime_v10/src/runtime/policy.rs
> Fix bigint serialization

- Cargo.lock
- Cargo.toml
- Makefile
- fil_actor_interface/Cargo.toml
- fil_actor_interface/src/builtin/miner/mod.rs
> fix(ci): remove protoc from all places

- .github/workflows/tests.yml
- README.md
- codecov ci job
- badges in readme.md
Closes 
> feat(ci): codecov and badges

- Cargo.lock
- Cargo.toml
- evm_v10/shared_v10/Cargo.toml
- evm_v10/shared_v10/src/address.rs
- evm_v10/shared_v10/src/uints.rs
- runtime_v10/Cargo.toml
- runtime_v10/src/runtime/policy.rs
- runtime_v10/tests/policy_test.rs
See https://github.com/ChainSafe/fil-actor-states/issues/2#issuecomment-1475817989
Closes 
> fix: bigint toml serde in `Policy`

- runtime_v10/src/runtime/empty.rs
- I am unsure why this file was removed, but this is a valuable utility for state migrations. Either we need to redefine all such utilities in Forest or don't delete them from builtin-actors source.
Closes 
> revive empty.rs

- fil_actor_interface/src/builtin/miner/mod.rs
- fil_actor_interface/src/builtin/power/mod.rs
- fil_actor_interface/src/lib.rs
- Export `Policy` from `fil_actor_interface` so that users of `fil_actor_states` can use this `Policy` and stay up-to date.
Closes #68 
> Export Policy from fil actor interface

- .github/workflows/tests.yml
- .gitmodules
- Makefile
- Added `forest` as submodule
- Automated `forest` build, test and calibnet sync check
Closes #69 
> Added forest compact check in CI

- Cargo.lock
- runtime_v10/Cargo.toml
- runtime_v10/tests/policy_test.rs
- make `arb` dependency explicit.
- remove unnecessary self-dependency.
Closes 
> chore: specify that policy round-trip test depends on the arb feature

- .gitmodules
> chore: redirect submodule to main branch

- fil_actor_interface/src/builtin/mod.rs
- fix copy&paste error in `is_eth_account_actor`
Closes 
> fix: is_eth_account_actor typo

- Cargo.lock
- Cargo.toml
- actors/account/Cargo.toml
- actors/cron/Cargo.toml
- actors/datacap/Cargo.toml
- actors/eam/Cargo.toml
- actors/ethaccount/Cargo.toml
- actors/evm/Cargo.toml
- actors/evm_shared/Cargo.toml
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/reward/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
- fil_actor_interface/Cargo.toml
- fil_actors_shared/Cargo.toml
- scripts/find_duplicate_deps.rb
- Changed version to 4.0.0
Closes #118 
> Prepare release v4.0.0

- Cargo.lock
- Cargo.toml
- actors/init/Cargo.toml
- actors/init/src/lib.rs
- actors/init/src/v0/mod.rs
- actors/init/src/v0/state.rs
- actors/init/src/v0/types.rs
- fil_actor_interface/src/builtin/init/mod.rs
- fil_actor_interface/src/builtin/known_cids.rs
- Added v0 init actor and updated `fil_actor_interface` crate.
- Added `INIT_V0_ACTOR_CID` to `test_loading_static_value`.
Closes #123 
> Added Init V0 actor

- .github/workflows/publish-release.yml
- Cargo.lock
- actors/account/Cargo.toml
- actors/cron/Cargo.toml
- actors/datacap/Cargo.toml
- actors/eam/Cargo.toml
- actors/ethaccount/Cargo.toml
- actors/evm/Cargo.toml
- actors/evm_shared/Cargo.toml
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/reward/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
- fil_actor_interface/Cargo.toml
- fil_actors_shared/Cargo.toml
- Updated version from v4.0.0 to v5.0.0
- made corrections in publish-release.yml
Closes 
> Prepare Release v5.0.0

- Cargo.lock
- fil_actor_interface/Cargo.toml
- `fil_actor_interface` version updated to v5.1.0
Closes #141 
> Prepare Release fil_actor_interface v5.1.0

- .github/release-checklist.md
- Added release checklist to publish all crates to crates.io.
Closes 
> Release checklist

- Cargo.lock
- actors/account/Cargo.toml
- actors/cron/Cargo.toml
- actors/datacap/Cargo.toml
- actors/eam/Cargo.toml
- actors/ethaccount/Cargo.toml
- actors/evm/Cargo.toml
- actors/evm_shared/Cargo.toml
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/reward/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
- fil_actor_interface/Cargo.toml
- fil_actors_shared/Cargo.toml
Part of https://github.com/ChainSafe/forest/issues/3478 and https://github.com/ChainSafe/forest/issues/3422
- Bump crate versions and prepare for a new release to unblock https://github.com/ChainSafe/forest/pull/3481
Closes 
> chore: prepare for 6.1.0 release

- Cargo.lock
- Makefile
- actors/account/Cargo.toml
- actors/cron/Cargo.toml
- actors/datacap/Cargo.toml
- actors/eam/Cargo.toml
- actors/ethaccount/Cargo.toml
- actors/evm/Cargo.toml
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/reward/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
- fil_actor_interface/Cargo.toml
- fil_actors_shared/Cargo.toml
> Prepare release for v12.0.0-rc.2 

- Cargo.lock
- fil_actor_interface/Cargo.toml
- fil_actor_interface/src/builtin/miner/mod.rs
> add buggy miner cid to v12 miner

- Cargo.lock
- actors/account/Cargo.toml
- actors/cron/Cargo.toml
- actors/datacap/Cargo.toml
- actors/eam/Cargo.toml
- actors/ethaccount/Cargo.toml
- actors/evm/Cargo.toml
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/reward/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
- fil_actor_interface/Cargo.toml
- fil_actors_shared/Cargo.toml
> Prepare release for v7.0.0-rc.3

- Cargo.lock
- actors/account/Cargo.toml
- actors/cron/Cargo.toml
- actors/datacap/Cargo.toml
- actors/eam/Cargo.toml
- actors/ethaccount/Cargo.toml
- actors/evm/Cargo.toml
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/reward/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
- fil_actor_interface/Cargo.toml
- fil_actors_shared/Cargo.toml
> Prepare new release v7.0.0-rc.4

- Cargo.lock
- actors/account/Cargo.toml
- actors/cron/Cargo.toml
- actors/datacap/Cargo.toml
- actors/eam/Cargo.toml
- actors/ethaccount/Cargo.toml
- actors/evm/Cargo.toml
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/reward/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
- fil_actor_interface/Cargo.toml
- fil_actors_shared/Cargo.toml
> Prepare release v7.0.0-rc.5

- actors/miner/src/v10/expiration_queue.rs
- actors/miner/src/v11/expiration_queue.rs
- rust-toolchain.toml
- upgrade rust toolchain to 1.74.0
- update forest submodule
- fix clippy warnings
Closes 
> chore: upgrade rust toolchain to 1.74.0

- fil_actor_interface/src/builtin/miner/mod.rs
- fil_actors_shared/Cargo.toml
- Make sure we can enable `json` feature for `fvm_ipld_bitfield`.
Closes 
Helps https://github.com/ChainSafe/forest/pull/3726
> [Chore] Propagate json feature to fvm_ipld_bitfield.

- fil_actor_interface/src/builtin/miner/mod.rs
- fil_actor_interface/src/convert.rs
- Update MinerInfo to conform to Lotus v0 rpc.
work on https://github.com/ChainSafe/forest/issues/3639 
> [Chore] Update MinerInfo

- Cargo.lock
- actors/account/Cargo.toml
- actors/cron/Cargo.toml
- actors/datacap/Cargo.toml
- actors/eam/Cargo.toml
- actors/ethaccount/Cargo.toml
- actors/evm/Cargo.toml
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/reward/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
- fil_actor_interface/Cargo.toml
- fil_actors_shared/Cargo.toml
> Prepare new release v8.0.0

- .github/workflows/tests.yml
- Pin rubocop version to v1.57
Closes 
> Pin rubocop version in CI

- Cargo.lock
- actors/account/Cargo.toml
- actors/cron/Cargo.toml
- actors/datacap/Cargo.toml
- actors/eam/Cargo.toml
- actors/ethaccount/Cargo.toml
- actors/evm/Cargo.toml
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/reward/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
- fil_actor_interface/Cargo.toml
- fil_actors_shared/Cargo.toml
> Prepare new v9.0.0 release

- fil_actor_interface/build.rs
- fil_actor_interface/src/builtin/actor_cids.yaml
- fil_actor_interface/src/builtin/known_cids.rs
- fil_actor_interface/src/builtin/manifest_cids.yaml
- added butterflynet actors support,
- the CIDs were generated automatically (hence the order is shuffled), but the code to do this is a mess and outside of the scope of this PR. I'll add it in a follow-up PR.
- fixed a v11 mainnet manifest Cid which was incorrectly, manually added.
Closes 
> add butterflynet support

- .github/workflows/tests.yml
- README.md
- deleted coverage reports, given they provided no value to the project
Closes 
> delete coverage reports

- Cargo.lock
- Cargo.toml
- actors/datacap/Cargo.toml
- actors/evm/Cargo.toml
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/verifreg/Cargo.toml
- fil_actor_interface/Cargo.toml
> Prepare release v9.2.0

- Cargo.lock
- Cargo.toml
- actors/datacap/Cargo.toml
- actors/evm/Cargo.toml
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/verifreg/Cargo.toml
- fil_actor_interface/Cargo.toml
- Updated version to v9.3.0
Closes 
> Prepare new release v9.3.0

- Cargo.lock
- actors/verifreg/src/v8/state.rs
- fil_actor_interface/Cargo.toml
- fil_actor_interface/src/builtin/datacap/mod.rs
- fil_actor_interface/src/builtin/verifreg/mod.rs
- fil_actors_shared/src/lib.rs
- State::load for verifreg and other tweaks to support getting data caps. 
work on https://github.com/ChainSafe/forest/pull/3817 
> [Feature] State::load for verifreg and datacap.

- Cargo.lock
- Cargo.toml
- actors/datacap/Cargo.toml
- actors/evm/Cargo.toml
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/verifreg/Cargo.toml
- fil_actor_interface/Cargo.toml
> Prepare new release v9.4.0

- Cargo.lock
- Cargo.toml
- actors/datacap/Cargo.toml
- actors/evm/Cargo.toml
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
- fil_actor_interface/Cargo.toml
- prepare development release for NV22
Closes 
> prepare release 10.0.0-dev.1

- .github/release-checklist.md
- update release checklist with a less error-prone flow (use GH releases via UI and not command line)
Closes 
> update release checklist

- Cargo.lock
- Cargo.toml
- actors/datacap/Cargo.toml
- actors/evm/Cargo.toml
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
- fil_actor_interface/Cargo.toml
- Updated version to "10.0.0-rc.2"
Closes 
> Prepare new release v10.0.0-rc.2

- Cargo.toml
- actors/datacap/Cargo.toml
- actors/evm/Cargo.toml
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
- fil_actor_interface/Cargo.toml
- fil_actor_interface/builtin_actors_gen.go
- https://github.com/filecoin-project/builtin-actors/releases/tag/v13.0.0-rc.3, this will be used for calibnet upgrade (most likely)
- release including updated actors 
Closes 
> Prepare v10.0.0 dev.3

- Cargo.lock
- Cargo.toml
- actors/datacap/Cargo.toml
- actors/evm/Cargo.toml
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
- fil_actor_interface/Cargo.toml
- forgot to update the lockfile for the last release,
Closes 
> prepare release v10.0.0-dev.4

- Cargo.lock
- Cargo.toml
- actors/datacap/Cargo.toml
- actors/evm/Cargo.toml
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
- fil_actor_interface/Cargo.toml
- fil_actor_interface/builtin_actors_gen.go
- prepare release `10.0.0` that contains CID changes for the [v13.0.0](https://github.com/filecoin-project/builtin-actors/releases/tag/v13.0.0) release of `builtin-actors`. Note that a change for the calibration network may come later.
Closes 
> prepare release 10.0.0

- Cargo.toml
- Makefile
- actors/datacap/Cargo.toml
- actors/evm/Cargo.toml
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
- fil_actor_interface/Cargo.toml
- Release v10.1.1
Closes 
This release takes care of the changes needed for `Filecoin.StateDealProviderCollateralBounds` RPC endpoint compatibility.
> [Release] v10.1.1

- Cargo.toml
- actors/datacap/Cargo.toml
- actors/evm/Cargo.toml
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
- fil_actor_interface/Cargo.toml
- v11.0.0 release
Closes 
- Refactor TokenAmount conversions to receive pointers, making the API more efficient.
- Refactor reward::State to achieve a more eloquent and performant API.
> [Release] v11.0.0

- Cargo.toml
- actors/datacap/Cargo.toml
- actors/evm/Cargo.toml
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/market/src/v10/state.rs
- actors/market/src/v11/state.rs
- actors/market/src/v12/state.rs
- actors/market/src/v13/state.rs
- actors/market/src/v8/state.rs
- actors/market/src/v9/state.rs
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
- fil_actor_interface/Cargo.toml
- fil_actor_interface/src/builtin/market/mod.rs
- fil_actors_shared/src/v8/actor_error.rs
- impl missing escrow_table and locked_table API to unblock https://github.com/ChainSafe/forest/pull/4186
Closes 
> feat: impl missing escrow_table and locked_table API

- Cargo.toml
- actors/datacap/Cargo.toml
- actors/evm/Cargo.toml
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/reward/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
- fil_actor_interface/Cargo.toml
> Prepare new release v11.2.0

- Cargo.toml
- actors/datacap/Cargo.toml
- actors/evm/Cargo.toml
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/reward/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
- fil_actor_interface/Cargo.toml
> New Release v12.0.0

- fil_actor_interface/src/builtin/verifreg/mod.rs
- Export un-versioned `Allocation` and `AllocationID`.
- Add `get_allocation` method.
Closes 
> feat: general interface to allocations

- Cargo.toml
- actors/datacap/Cargo.toml
- actors/evm/Cargo.toml
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/reward/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
- fil_actor_interface/Cargo.toml
- release latest changes
Closes 
> [Release] v13.0.0

- Cargo.toml
- Updated version to `v15.0.0`
> Prepare release v15.0.0

- .github/composite-actions/publish-crate/action.yml
- .github/workflows/publish.yml
- Fix `action.yml` accessibility
> Fix Publish 

- .github/composite-actions/publish-crate/action.yml
- .github/workflows/publish.yml
- Fix `action.yml`: remove timeout-minutes
Closes 
> Fix publish composite action

- Cargo.toml
- Bump version to v15.2.0
Closes 
> Prepare v15.2.0 release

- fil_actor_interface/src/builtin/multisig/mod.rs
- Fix argument to `locked_amount`. It should be elapsed epochs, not an absolute epoch.
Closes 
> fix: copy/paste mistake in `multisig::locked_balance`

- Cargo.toml
- This release fixes `locked_balance`.
Closes 
> release: v16.0.1

- README.md
- added reasoning to the repo's existence.
Closes 
> doc: add repo reasoning to README

- Cargo.toml
- prepare release 17.0.1 that contains dependency updates from https://github.com/ChainSafe/fil-actor-states/pull/332 and https://github.com/ChainSafe/fil-actor-states/pull/333
Closes 
> chore: prepare release 17.0.1

- .github/workflows/tests.yml
- Cargo.toml
- Makefile
- check_crates.sh
- fil_actors_shared/Cargo.toml
- fix missing deps issue,
- introduce test to catch future regressions,
- prepare release v17.0.2
Closes 
> fix: check crates individually

- actors/market/src/v10/state.rs
- actors/market/src/v11/state.rs
- actors/market/src/v12/state.rs
- actors/market/src/v13/state.rs
- actors/market/src/v14/state.rs
- actors/market/src/v15/state.rs
- this is a fix for https://github.com/ChainSafe/forest/issues/4890
- long-term we should not add methods to the state files and the existing ones should be migrated to extension traits. https://github.com/ChainSafe/fil-actor-states/issues/338
Closes 
https://github.com/filecoin-project/go-state-types/blob/3e503e60521297fdc1eae0aaf837bdbb3eacf8c2/builtin/v14/market/market_state.go#L195-L202
> fix: incorrect deal weight calculation

- .gitmodules
- Cargo.toml
- prepared release v17.0.3
Closes 
> prepare release v17.0.3

- actors/evm/src/evm_shared/v10/uints.rs
- actors/evm/src/evm_shared/v11/uints.rs
- actors/evm/src/evm_shared/v12/uints.rs
- actors/evm/src/evm_shared/v13/uints.rs
- actors/evm/src/evm_shared/v14/uints.rs
- actors/evm/src/evm_shared/v15/uints.rs
- actors/market/src/v10/state.rs
- actors/market/src/v11/state.rs
- actors/market/src/v12/state.rs
- fil_actors_shared/src/v10/runtime/policy.rs
- fil_actors_shared/src/v10/util/set.rs
- fil_actors_shared/src/v11/runtime/policy.rs
- fil_actors_shared/src/v11/util/set.rs
- fil_actors_shared/src/v12/util/set.rs
- fil_actors_shared/src/v13/util/set.rs
- fil_actors_shared/src/v8/util/set.rs
- fil_actors_shared/src/v9/runtime/policy.rs
- fil_actors_shared/src/v9/util/set.rs
- rust-toolchain.toml
- upgrade rust toolchain
- fix clippy warnings
Closes 
> chore: upgrade rust toolchain

- .github/workflows/publish.yml
- actors/eam/Cargo.toml
- actors/eam/src/v10/mod.rs
- actors/eam/src/v11/mod.rs
- actors/eam/src/v12/mod.rs
- actors/eam/src/v13/mod.rs
- actors/eam/src/v14/mod.rs
- actors/eam/src/v15/mod.rs
- fil_actors_shared/src/abi/commp.rs
- Added EAM types
- Update `fil_actor_eam_state` publish workflow due to introduced dependency on `fil_actor_evm_state` 
Closes #345 
> Added EAM types

- Cargo.toml
- actors/evm/src/v16/state.rs
- update v16 actor with new release of [v16.0.0-dev1](https://github.com/filecoin-project/builtin-actors/releases/tag/v16.0.0-dev1)
Contributes to https://github.com/ChainSafe/forest/issues/5136 
> Update V16 actors

- Cargo.toml
- actors/miner/src/v12/state.rs
- actors/miner/src/v13/state.rs
- actors/miner/src/v14/state.rs
- actors/miner/src/v15/state.rs
- actors/miner/src/v16/state.rs
part of https://github.com/ChainSafe/forest/issues/5351
Forest PR: https://github.com/ChainSafe/forest/pull/5417
- 
Closes 
> chore: upgrade fvm_shared to 4.6

- Cargo.toml
- actors/miner/src/v16/vesting_state.rs
To unblock https://github.com/ChainSafe/forest/pull/5431
- 
Closes 
> fix: make VestingFunds::save public

- Cargo.toml
- actors/miner/src/v16/vesting_state.rs
- Set `VestingFundsInner` struct as `pub`
- Update version to `v22.1.0`
Closes 
> Expose `VestingFundsInner` struct

- Cargo.toml
- actors/miner/src/v16/vesting_state.rs
-  Make `VestingFundsInner` internal fields public
- Update version to v22.2.0
Closes 
> Expose v16 miner VestingFundsInner internal fields

- Cargo.toml
- Update the `frc46` token crate to it's latest version (14.0.1)
- Update release version to v22.3.0
Closes 
> chore(deps): update `frc46` token crate version

- fil_actors_shared/Cargo.toml
- fil_actors_shared/src/actor_versions.rs
- fil_actors_shared/src/lib.rs
- Introduced an `ActorVersion` enum in the `fil-actor-shared` to track all the supported version at one place
- This will be helpful in the [forest](https://github.com/ChainSafe/forest/issues/5937) 
Closes 
> Add actor versions in the `fil-actor-shared`

- Makefile
- Add `fil_actor_ethaccount_state` support in the `modify-forest` make cmd
Closes  #388 
> Add fil_actor_ethaccount_state in Makefile
